export type ThemeMode = 'light' | 'dark' | 'system';

export type ColorPalette = 'blue' | 'green' | 'purple' | 'orange' | 'red' | 'teal' | 'rose' | 'slate' | 'emerald' | 'indigo';

export interface Theme {
  mode: ThemeMode;
  palette: ColorPalette;
}

export interface ThemeColors {
  // Background colors
  background: string;
  surface: string;
  surfaceHover: string;

  // Text colors
  foreground: string;
  foregroundSecondary: string;
  foregroundMuted: string;

  // Primary colors (theme palette)
  primary: string;
  primaryHover: string;
  primaryForeground: string;

  // Secondary colors
  secondary: string;
  secondaryHover: string;
  secondaryForeground: string;

  // Border colors
  border: string;
  borderHover: string;

  // Status colors
  success: string;
  warning: string;
  error: string;
  info: string;

  // Gradient colors
  gradientFrom: string;
  gradientTo: string;
}

export const colorPalettes: Record<ColorPalette, { light: ThemeColors; dark: ThemeColors }> = {
  blue: {
    light: {
      background: '#ffffff',
      surface: '#f8fafc',
      surfaceHover: '#f1f5f9',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#3b82f6',
      primaryHover: '#2563eb',
      primaryForeground: '#ffffff',
      secondary: '#e2e8f0',
      secondaryHover: '#cbd5e1',
      secondaryForeground: '#b8bdc4ff',
      border: '#e2e8f0',
      borderHover: '#cbd5e1',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#dbeafe',
      gradientTo: '#e0e7ff',
    },
    dark: {
      background: '#0f172a',
      surface: '#1e293b',
      surfaceHover: '#334155',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#60a5fa',
      primaryHover: '#3b82f6',
      primaryForeground: '#1e293b',
      secondary: '#334155',
      secondaryHover: '#b8bdc4ff',
      secondaryForeground: '#cbd5e1',
      border: '#334155',
      borderHover: '#b8bdc4ff',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#1e293b',
      gradientTo: '#334155',
    },
  },
  green: {
    light: {
      background: '#ffffff',
      surface: '#f6fdf9',
      surfaceHover: '#ecfdf5',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#10b981',
      primaryHover: '#059669',
      primaryForeground: '#ffffff',
      secondary: '#dcfce7',
      secondaryHover: '#bbf7d0',
      secondaryForeground: '#166534',
      border: '#d1fae5',
      borderHover: '#bbf7d0',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#dcfce7',
      gradientTo: '#d1fae5',
    },
    dark: {
      background: '#0a0f0a',
      surface: '#1a2e1a',
      surfaceHover: '#2d4a2d',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#34d399',
      primaryHover: '#10b981',
      primaryForeground: '#0a0f0a',
      secondary: '#2d4a2d',
      secondaryHover: '#3d5a3d',
      secondaryForeground: '#cbd5e1',
      border: '#2d4a2d',
      borderHover: '#3d5a3d',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#1a2e1a',
      gradientTo: '#2d4a2d',
    },
  },
  purple: {
    light: {
      background: '#ffffff',
      surface: '#faf8ff',
      surfaceHover: '#f5f3ff',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#8b5cf6',
      primaryHover: '#7c3aed',
      primaryForeground: '#ffffff',
      secondary: '#ede9fe',
      secondaryHover: '#ddd6fe',
      secondaryForeground: '#5b21b6',
      border: '#e9d5ff',
      borderHover: '#ddd6fe',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#ede9fe',
      gradientTo: '#e9d5ff',
    },
    dark: {
      background: '#0f0a1a',
      surface: '#1e1a2e',
      surfaceHover: '#2e2a4a',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#a78bfa',
      primaryHover: '#8b5cf6',
      primaryForeground: '#0f0a1a',
      secondary: '#2e2a4a',
      secondaryHover: '#3e3a5a',
      secondaryForeground: '#cbd5e1',
      border: '#2e2a4a',
      borderHover: '#3e3a5a',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#1e1a2e',
      gradientTo: '#2e2a4a',
    },
  },
  orange: {
    light: {
      background: '#ffffff',
      surface: '#fffaf8',
      surfaceHover: '#fff7ed',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#f97316',
      primaryHover: '#ea580c',
      primaryForeground: '#ffffff',
      secondary: '#fed7aa',
      secondaryHover: '#fdba74',
      secondaryForeground: '#9a3412',
      border: '#fed7aa',
      borderHover: '#fdba74',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#fed7aa',
      gradientTo: '#fef3c7',
    },
    dark: {
      background: '#1a0f0a',
      surface: '#2e1a0f',
      surfaceHover: '#4a2d1a',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#fb923c',
      primaryHover: '#f97316',
      primaryForeground: '#1a0f0a',
      secondary: '#4a2d1a',
      secondaryHover: '#5a3d2a',
      secondaryForeground: '#cbd5e1',
      border: '#4a2d1a',
      borderHover: '#5a3d2a',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#2e1a0f',
      gradientTo: '#4a2d1a',
    },
  },
  red: {
    light: {
      background: '#ffffff',
      surface: '#fef8f8',
      surfaceHover: '#fef2f2',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#ef4444',
      primaryHover: '#dc2626',
      primaryForeground: '#ffffff',
      secondary: '#fecaca',
      secondaryHover: '#fca5a5',
      secondaryForeground: '#991b1b',
      border: '#fecaca',
      borderHover: '#fca5a5',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#fecaca',
      gradientTo: '#fed7d7',
    },
    dark: {
      background: '#1a0a0a',
      surface: '#2e1a1a',
      surfaceHover: '#4a2d2d',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#f87171',
      primaryHover: '#ef4444',
      primaryForeground: '#1a0a0a',
      secondary: '#4a2d2d',
      secondaryHover: '#5a3d3d',
      secondaryForeground: '#cbd5e1',
      border: '#4a2d2d',
      borderHover: '#5a3d3d',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#2e1a1a',
      gradientTo: '#4a2d2d',
    },
  },
  teal: {
    light: {
      background: '#ffffff', 
      surface: '#f7fffe',
      surfaceHover: '#f0fdfa',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#14b8a6',
      primaryHover: '#0d9488',
      primaryForeground: '#ffffff',
      secondary: '#ccfbf1',
      secondaryHover: '#99f6e4',
      secondaryForeground: '#134e4a',
      border: '#ccfbf1',
      borderHover: '#99f6e4',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#ccfbf1',
      gradientTo: '#a7f3d0',
    },
    dark: {
      background: '#0a1a1a',
      surface: '#1a2e2e',
      surfaceHover: '#2d4a4a',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#5eead4',
      primaryHover: '#14b8a6',
      primaryForeground: '#0a1a1a',
      secondary: '#2d4a4a',
      secondaryHover: '#3d5a5a',
      secondaryForeground: '#cbd5e1',
      border: '#2d4a4a',
      borderHover: '#3d5a5a',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#1a2e2e',
      gradientTo: '#2d4a4a',
    },
  },
  rose: {
    light: {
      background: '#ffffff',
      surface: '#fef7f7',
      surfaceHover: '#fef2f2',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#e11d48',
      primaryHover: '#be185d',
      primaryForeground: '#ffffff',
      secondary: '#fecdd3',
      secondaryHover: '#fda4af',
      secondaryForeground: '#881337',
      border: '#fecdd3',
      borderHover: '#fda4af',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#fecdd3',
      gradientTo: '#fed7d7',
    },
    dark: {
      background: '#0f0a0d',
      surface: '#2e1a20',
      surfaceHover: '#4a2d35',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#fb7185',
      primaryHover: '#e11d48',
      primaryForeground: '#0f0a0d',
      secondary: '#4a2d35',
      secondaryHover: '#5a3d45',
      secondaryForeground: '#cbd5e1',
      border: '#4a2d35',
      borderHover: '#5a3d45',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#2e1a20',
      gradientTo: '#4a2d35',
    },
  },
  slate: {
    light: {
      background: '#ffffff',
      surface: '#f8fafc',
      surfaceHover: '#f1f5f9',
      foreground: '#0f172a',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#b8bdc4ff',
      primaryHover: '#334155',
      primaryForeground: '#ffffff',
      secondary: '#e2e8f0',
      secondaryHover: '#cbd5e1',
      secondaryForeground: '#b8bdc4ff',
      border: '#e2e8f0',
      borderHover: '#cbd5e1',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#f8fafc',
      gradientTo: '#e2e8f0',
    },
    dark: {
      background: '#020617',
      surface: '#1e293b',
      surfaceHover: '#334155',
      foreground: '#f8fafc',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#94a3b8',
      primaryHover: '#cbd5e1',
      primaryForeground: '#020617',
      secondary: '#334155',
      secondaryHover: '#b8bdc4ff',
      secondaryForeground: '#cbd5e1',
      border: '#334155',
      borderHover: '#b8bdc4ff',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#1e293b',
      gradientTo: '#334155',
    },
  },
  emerald: {
    light: {
      background: '#ffffff',
      surface: '#f0fdf4',
      surfaceHover: '#ecfdf5',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#059669',
      primaryHover: '#047857',
      primaryForeground: '#ffffff',
      secondary: '#d1fae5',
      secondaryHover: '#bbf7d0',
      secondaryForeground: '#064e3b',
      border: '#d1fae5',
      borderHover: '#bbf7d0',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#d1fae5',
      gradientTo: '#a7f3d0',
    },
    dark: {
      background: '#022c22',
      surface: '#064e3b',
      surfaceHover: '#047857',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#34d399',
      primaryHover: '#10b981',
      primaryForeground: '#022c22',
      secondary: '#047857',
      secondaryHover: '#059669',
      secondaryForeground: '#cbd5e1',
      border: '#047857',
      borderHover: '#059669',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#064e3b',
      gradientTo: '#047857',
    },
  },
  indigo: {
    light: {
      background: '#ffffff',
      surface: '#fafaff',
      surfaceHover: '#f5f3ff',
      foreground: '#1e293b',
      foregroundSecondary: '#1e293b',
      foregroundMuted: '#64748b',
      primary: '#4f46e5',
      primaryHover: '#4338ca',
      primaryForeground: '#ffffff',
      secondary: '#e0e7ff',
      secondaryHover: '#c7d2fe',
      secondaryForeground: '#3730a3',
      border: '#e0e7ff',
      borderHover: '#c7d2fe',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      info: '#3b82f6',
      gradientFrom: '#e0e7ff',
      gradientTo: '#c7d2fe',
    },
    dark: {
      background: '#1e1b4b',
      surface: '#312e81',
      surfaceHover: '#3730a3',
      foreground: '#f1f5f9',
      foregroundSecondary: '#ffffff',
      foregroundMuted: '#94a3b8',
      primary: '#818cf8',
      primaryHover: '#6366f1',
      primaryForeground: '#1e1b4b',
      secondary: '#3730a3',
      secondaryHover: '#4338ca',
      secondaryForeground: '#cbd5e1',
      border: '#3730a3',
      borderHover: '#4338ca',
      success: '#34d399',
      warning: '#fbbf24',
      error: '#f87171',
      info: '#60a5fa',
      gradientFrom: '#312e81',
      gradientTo: '#3730a3',
    },
  },
};